export const SolidColors = [
  { name: "Red", value: "#ff0000" },
  { name: "Green", value: "#00ff00" },
  { name: "Blue", value: "#0000ff" },
  { name: "Yellow", value: "#ffff00" },
  { name: "Orange", value: "#ff7f00" },
  { name: "Purple", value: "#800080" },
  { name: "Pink", value: "#ffc0cb" },
  { name: "Brown", value: "#a52a2a" },
  { name: "Black", value: "#000000" },
  { name: "White", value: "#ffffff" },
  { name: "Gray", value: "#808080" },
  { name: "Silver", value: "#c0c0c0" },
  { name: "Gold", value: "#ffd700" },
  { name: "Cyan", value: "#00ffff" },
  { name: "Magenta", value: "#ff00ff" },
  { name: "Lime", value: "#00ff00" },
  { name: "Teal", value: "#008080" },
  { name: "Maroon", value: "#800000" },
  { name: "Navy", value: "#000080" },
  { name: "Olive", value: "#808000" },
  { name: "Indigo", value: "#4b0082" },
  { name: "Turquoise", value: "#40e0d0" },
  { name: "Violet", value: "#ee82ee" },
  { name: "Crimson", value: "#dc143c" },
  { name: "Plum", value: "#dda0dd" },
  { name: "Chocolate", value: "#d2691e" },
  { name: "Saddle Brown", value: "#8b4513" },
  { name: "Dark Red", value: "#8b0000" },
  { name: "Dark Green", value: "#006400" },
  { name: "Dark Blue", value: "#00008b" },
  { name: "Dark Yellow", value: "#ffff00" },
  { name: "Dark Orange", value: "#ff8c00" },
  { name: "Dark Purple", value: "#800080" },
  { name: "Dark Pink", value: "#ff1493" },
  { name: "Dark Brown", value: "#a52a2a" },
  { name: "Dark Gray", value: "#a9a9a9" },
  { name: "Dark Silver", value: "#c0c0c0" },
  { name: "Dark Gold", value: "#ffd700" },
  { name: "Dark Cyan", value: "#00ffff" },
  { name: "Dark Magenta", value: "#ff00ff" },
  { name: "Dark Lime", value: "#00ff00" },
  { name: "Dark Teal", value: "#008080" },
  { name: "Dark Maroon", value: "#800000" },
  { name: "Dark Navy", value: "#000080" },
  { name: "Dark Olive", value: "#808000" },
  { name: "Dark Indigo", value: "#4b0082" },
  { name: "Dark Turquoise", value: "#40e0d0" },
  { name: "Dark Violet", value: "#ee82ee" },
  { name: "Dark Crimson", value: "#dc143c" },
  { name: "Dark Plum", value: "#dda0dd" },
  { name: "Dark Chocolate", value: "#d2691e" },
  { name: "Dark Saddle Brown", value: "#8b4513" },
  { name: "Dark Red", value: "#8b0000" },
  { name: "Dark Green", value: "#006400" },
  { name: "Dark Blue", value: "#00008b" },
  { name: "Dark Yellow", value: "#ffff00" },
  { name: "Dark Orange", value: "#ff8c00" },
  { name: "Dark Purple", value: "#800080" },
  { name: "Dark Pink", value: "#ff1493" },
  { name: "Dark Brown", value: "#a52a2a" },
  { name: "Dark Gray", value: "#a9a9a9" },
  { name: "Dark Silver", value: "#c0c0c0" },
  { name: "Dark Gold", value: "#ffd700" },
  { name: "Dark Cyan", value: "#00ffff" },
  { name: "Dark Magenta", value: "#ff00ff" },
  { name: "Dark Lime", value: "#00ff00" },
  { name: "Dark Teal", value: "#008080" },
  { name: "Dark Maroon", value: "#800000" },
  { name: "Dark Navy", value: "#000080" },
  { name: "Dark Olive", value: "#808000" },
  { name: "Dark Indigo", value: "#4b0082" },
  { name: "Dark Turquoise", value: "#40e0d0" },
  { name: "Dark Violet", value: "#ee82ee" },
  { name: "Dark Crimson", value: "#dc143c" },
  { name: "Dark Plum", value: "#dda0dd" },
];

export const GradientColors = [
  { name: "Red", gradient: "linear-gradient(to right, #ff0000, #ffA07A)" },
  { name: "Green", gradient: "linear-gradient(to right, #00ff00, #90EE90)" },
  { name: "Blue", gradient: "linear-gradient(to right, #0000ff, #87CEEB)" },
  { name: "Yellow", gradient: "linear-gradient(to right, #ffff00, #FFFFE0)" },
  { name: "Orange", gradient: "linear-gradient(to right, #ffA500, #FFD700)" },  
  { name: "Purple", gradient: "linear-gradient(to right, #800080, #9370DB)" },
  { name: "Pink", gradient: "linear-gradient(to right, #ff1493, #FFC0CB)" },
  { name: "Brown", gradient: "linear-gradient(to right, #a52a2a, #D2B48C)" },
  { name: "Gray", gradient: "linear-gradient(to right, #a9a9a9, #D3D3D3)" },
  { name: "Silver", gradient: "linear-gradient(to right, #c0c0c0, #C0C0C0 )" },
  { name: "Gold", gradient: "linear-gradient(to right, #ffd700, #FFF7F0)" },
  { name: "Cyan", gradient: "linear-gradient(to right, #00ffff, #B0E0E6)" },
  { name: "Magenta", gradient: "linear-gradient(to right, #ff00ff, #FFC0CB)" },
  { name: "Lime", gradient: "linear-gradient(to right, #00ff00, #98FB98)" },
  { name: "Teal", gradient: "linear-gradient(to right, #008080, #AFEEEE)" },
  { name: "Maroon", gradient: "linear-gradient(to right, #800000, #DB7093)" },
  { name: "Navy", gradient: "linear-gradient(to right, #000080, #0000FF)" },
  { name: "Olive", gradient: "linear-gradient(to right, #808000, #FDF5E6)" },
  { name: "Indigo", gradient: "linear-gradient(to right, #4b0082, #8A2BE2)" },
  { name: "Turquoise", gradient: "linear-gradient(to right, #40e0d0, #00CED1)" },
  { name: "Violet", gradient: "linear-gradient(to right, #ee82ee, #9370DB)" },
  { name: "Crimson", gradient: "linear-gradient(to right, #dc143c, #FF7F50)" },
  { name: "Plum", gradient: "linear-gradient(to right, #dda0dd, #AD00FF)" },
  { name: "Chocolate", gradient: "linear-gradient(to right, #d2691e, #DDFFAA)" },
  { name: "Saddle Brown", gradient: "linear-gradient(to right, #8b4513, #FFD700)" },
  { name: "Dark Red", gradient: "linear-gradient(to right, #8b0000, #FF0000)" },
  { name: "Dark Green", gradient: "linear-gradient(to right, #006400, #00FF00)" },
  { name: "Dark Blue", gradient: "linear-gradient(to right, #00008b, #0000FF)" },
  { name: "Dark Yellow", gradient: "linear-gradient(to right, #ffff00, #AAFF00)" },
  { name: "Dark Orange", gradient: "linear-gradient(to right, #ff7f00, #AA8C00)" },
  { name: "Dark Purple", gradient: "linear-gradient(to right, #800080, #FF00FF)" },
  { name: "Dark Pink", gradient: "linear-gradient(to right, #ff00ff, #FFC0CB)" },
  { name: "Dark Brown", gradient: "linear-gradient(to right, #a52a2a, #D2B48C)" },
  { name: "Dark Gray", gradient: "linear-gradient(to right, #a9a9a9, #D3D3D3)" },
  { name: "Dark Silver", gradient: "linear-gradient(to right, #c0c0c0, #C0C0C0 )" },
  { name: "Dark Gold", gradient: "linear-gradient(to right, #ffd700, #FFFFE0)" },
  { name: "Dark Cyan", gradient: "linear-gradient(to right, #00ffff, #B0E0E6)" },
  { name: "Dark Magenta", gradient: "linear-gradient(to right, #ff00ff, #FFC0CB)" },
  { name: "Dark Lime", gradient: "linear-gradient(to right, #00ff00, #98FB98)" },
  { name: "Dark Teal", gradient: "linear-gradient(to right, #008080, #AFEEEE)" },
  { name: "Dark Maroon", gradient: "linear-gradient(to right, #800000, #DB7093)" },
  { name: "Dark Navy", gradient: "linear-gradient(to right, #000080, #0000FF)" },
  { name: "Dark Olive", gradient: "linear-gradient(to right, #808000, #FDF5E6)" },
  { name: "Dark Indigo", gradient: "linear-gradient(to right, #4b0082, #8A2BE2)" },
  { name: "Dark Turquoise", gradient: "linear-gradient(to right, #40e0d0, #00CED1)" },
  { name: "Dark Violet", gradient: "linear-gradient(to right, #ee82ee, #9370DB)" },
  { name: "Dark Crimson", gradient: "linear-gradient(to right, #dc143c, #FF7F50)" },
  { name: "Dark Plum", gradient: "linear-gradient(to right, #dda0dd, #AD00FF)" },
  { name: "Dark Chocolate", gradient: "linear-gradient(to right, #d2691e, #DDFFAA)" },
  { name: "Dark Saddle Brown", gradient: "linear-gradient(to right, #8b4513, #FFD700)" },
  { name: "Dark Dark Red", gradient: "linear-gradient(to right, #8b0000, #FF0000)" },
  { name: "Dark Dark Green", gradient: "linear-gradient(to right, #006400, #00FF00)" },
  { name: "Dark Dark Blue", gradient: "linear-gradient(to right, #00008b, #0000FF)" },
  { name: "Dark Dark Yellow", gradient: "linear-gradient(to right, #ffff00, #AAFF00)" },
  { name: "Dark Dark Orange", gradient: "linear-gradient(to right, #ff7f00, #AA8C00)" },
  { name: "Dark Dark Purple", gradient: "linear-gradient(to right, #800080, #FF00FF)" },
  { name: "Dark Dark Pink", gradient: "linear-gradient(to right, #ff00ff, #FFC0CB)" },
  { name: "Dark Dark Brown", gradient: "linear-gradient(to right, #a52a2a, #D2B48C)" },
  { name: "Dark Dark Gray", gradient: "linear-gradient(to right, #a9a9a9, #D3D3D3)" },
  { name: "Dark Dark Silver", gradient: "linear-gradient(to right, #c0c0c0, #C0C0C0 )" },
  { name: "Dark Dark Gold", gradient: "linear-gradient(to right, #ffd700, #FFFFE0)" },
  { name: "Dark Dark Cyan", gradient: "linear-gradient(to right, #00ffff, #B0E0E6)" },
  { name: "Dark Dark Magenta", gradient: "linear-gradient(to right, #ff00ff, #FFC0CB)" },
  { name: "Dark Dark Lime", gradient: "linear-gradient(to right, #00ff00, #98FB98)" },
  { name: "Dark Dark Teal", gradient: "linear-gradient(to right, #008080, #AFEEEE)" },
  

];
